#!python3

import sys

def popular(password):
    mediocre = ['qqww1122', 'hottie', '7777777', 'letmein', 'donald', 'master', '123qwe', 'qwerty123',
                '12345', '1234', 'admin', 'adobe123', '12345678', 'michael', 'hello', 'shadow', '1234567',
                'bailey', '1234567890', 'whatever', 'iloveyou', '123123', 'Dragon', 'qazwsx', '!@#$%^&*',
                'solo', 'trustno1', 'photoshop', 'ninja', 'princess', 'Qwertyuiop', '123456789', 'Iloveyou',
                '1q2w3e4r', 'Million2', 'login', 'football', 'access', 'charlie', 'starwars', '18atcskd2w',
                '3rjs1la7qe', 'monkey', 'picture1', '12345679', '123321', '1q2w3e', 'aaron431', '1111111',
                'freedom', '123', 'flower', 'senha', '1q2w3e4r5t', 'mustang', 'zaq1zaq1', 'ashley', 'zxcvbnm',
                'mynoob', 'azerty', 'google', 'batman', '555555', '696969', '000000', '1qaz2wsx', 'jesus',
                'Monkey', 'Football', '987654321', 'abc123', '123456', 'qwertyuiop', '121212', 'baseball',
                'dragon', 'superman', 'aa123456', 'loveme', 'password1', 'password', '654321', '888888',
                '666666', 'qwerty', 'sunshine', 'passw0rd', 'lovely', '111111', 'welcome']
    return password in mediocre

def possibility(password):
    number = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]
    upper = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U","V","W", "X", "Y", "Z"]
    lower = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u","v", "w", "x", "y", "z"]
    symbol = ["~", "`", "!", "@", "#", "$", "%", "^", "&", "*", "(", ")", "_", "+", "-", "=", "{", "}", "[", "]", "|", "\\",  ":", ";", "'", '"', "<", ",", ">", ".", "?", "/"]
    result = 1
    for s in password:
        if s in number:
            result *= len(number)
        elif s in upper:
            result *= len(upper)
        elif s in lower:
            result *= len(lower)
        elif s in symbol:
            result *= len(symbol)
    return result

def print_period(msec):
    sec = int(msec / 1000)
    min  = int(sec / 60)
    hour = int(min / 60)
    days = int(hour / 24)
    mon = int(days / 30)
    year = int(mon / 12)
    myear = int(year / 10000)
    byear = int(myear / 10000)
    tyear = int(byear / 10000)
    qyear = int(tyear / 10000)

    print(str(min) + "分")
    print(str(hour) + "時間")
    print(str(days) + "日")
    print(str(mon) + "か月")
    print(str(year) + "年")
    print(str(myear) + "万年")
    print(str(byear) + "億年")
    print(str(tyear) + "兆年")
    print(str(qyear) + "京年")

args = sys.argv
if len(args) == 2:
    password = args[1]
    if len(password) > 4:
        if not popular(password):
            print_period(possibility(password))
        else:
            print("too popular.")
    else:
        print("too short.")
else:
    print("no arg.")
